### ISSUE TITLE
Find better way to add needed compiled solidity contracts rather than manually copying .json files 

### ISSUE THREAD

**Issue by pelsasser** [MarketProject/dApps-old#4]

**Comment by perfectmak** [comment]
Perhaps [Dapp](https://dapp.readthedocs.io/en/latest/package_management.html) can help with this. What do you think?

**Comment by pelsasser** [comment]
Sounds interesting, if I understand it correctly with allows the solidity source code to be imported like a library.  We would then still have to build and migrate in order to end up with the deployed contracts to interact with? This seems like a reasonable approach. 


Currently to get this running, I am deploying the other repository to the truffle environment  and then connecting to that.

**Comment by perfectmak** [comment]
Yeah. Ideally, a build step would be required to generate the ABI's from the source code, but I think this might be a duplicated step since the contracts are also built before deploying to the network.

So maybe an ideal solution would be to actually just find a way to publish the ABI's generated after the build in the other repository. So this dapp would just fetch from that and use it.

I'll look around to see how others actual try to automate this manual copying.
